version: 2


workflows:
  version: 2
  test:
    jobs:
      - gcc-7

jobs:
  gcc-7:
    docker:
      - image: enumack/buildcontainers:gcc-7

    steps:
      - checkout

      - run:
          name: Make Directory
          command: mkdir -p tests/build

      - run:
          name: CTest
          command: cd tests/build && cmake -DCMAKE_CXX_COMPILER=$CXX .. && make && make test

