version: 2
jobs:
  build:
    docker:
      - image: enumack/buildcontainers:gcc-7

    steps:
      - checkout

      - run:
          name: Make Directory
          command: mkdir -p tests/build

      - run:
          name: CTest
          command: cd tests/build && cmake .. && make && make test

clang_5_0:
    docker:
      - image: enumack/buildcontainers:clang-5.0

    steps:
      - checkout

      - run:
          name: Make Directory
          command: mkdir -p tests/build

      - run:
          name: CTest
          command: cd tests/build && cmake .. && make && make test

